# Dependencies
markdown:         redcarpet
highlighter:      pygments

permalink: /:categories/:title/
relative_permalinks: true

# Setup
title:            Project Log
tagline:          ''
description:      'Electronic, blog-style project log for my final year Computer Science project.'
url:              
baseurl:          /

author:
  name:           'Will Jones'
  url:            https://github.com/willjejones

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/willjejones/final-year-project
