# Dependencies
markdown:         redcarpet
highlighter:      rouge

permalink: /:categories/:title/

# Setup
title:            Producer Polaroids
tagline:          ''
description:      'Electronic, blog-style project log for my final year Computer Science project.'
url:              https://producerpolaroids.com
baseurl:          /

author:
  name:           'Will Jones'
  url:            https://github.com/willjejones

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/willjejones/final-year-project
