# Dependencies
highlighter:      rouge

permalink: /:categories/:title/

# Setup
title:            Producer Polaroids
tagline:          ''
description:      'Home of my producer polaroids - new track every Monday'
url:              https://producerpolaroids.com
baseurl:          /

author:
  name:           'Will Jones'
  url:            https://github.com/willjejones

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/willjejones/final-year-project

instagram:
  href:           https://www.instagram.com/willjejones/

soundcloud:
  href:           https://soundcloud.com/willjejones
