# Dependencies
markdown:         redcarpet
highlighter:      rouge

permalink: /:categories/:title/

# Setup
title:            Producer Polaroids
tagline:          ''
description:      'Home of my producer polaroids - new track every Monday'
url:              http://producerpolaroids.com
baseurl:          /

author:
  name:           'Will Jones'
  url:            https://github.com/willjejones

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/willjejones/final-year-project
