# Site settings
title: Project Log
email: william.jones@durham.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Will Jones' Project Log for his final year Computer Science project.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  willjejones

# Build settings
markdown: kramdown
