# Dependencies
highlighter:      rouge

permalink: /:categories/:title/

# Setup
title:            Producer Polaroids
tagline:          ''
description:      'Will Jones • New tracks every Sunday night'
url:              https://producerpolaroids.com
baseurl:          /

author:
  name:           'Will Jones'
  url:            https://github.com/willjejones

# Excerpt
excerpt_separator: <!--more-->

paginate: 5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/willjejones/final-year-project

# Google Analytics
google_analytics: UA-134868497-1

# Gems
plugins: [jekyll-paginate]